// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxrwlshmfgcnyfugbetw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4cndsc2htZmdjbnlmdWdiZXR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMzAzNjEsImV4cCI6MjA2MzcwNjM2MX0.ZPtnVEAKxVwb9Me7uYGL4lhtfNNfFLQRFIJqmA5wXdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);